_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 49
                - 51
                - 53
            "3":
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
alpha:
    value: 0.5
backbone:
    value: resnet18
batch_size:
    value: 512
checkpoints:
    value: ./checkpoints
data_root:
    value: /datastorage/li/eyepacs/augmented_resized_V2
dataset:
    value: eyepacs
epochs:
    value: 50
kfold:
    value: 1
lr:
    value: 0.0002
lr_policy:
    value: cosine
method:
    value: ordcls
optimizer:
    value: Adam
pretrained:
    value: true
results:
    value: ./results
seed:
    value: 42
task:
    value: classification
verbose:
    value: true
visible_gpus:
    value: "0"
weight_decay:
    value: 0.01
workers:
    value: 0
