_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 80
            "3":
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
backbone:
    value: vit
batch_size:
    value: 6
checkpoints:
    value: ./checkpoints
data_root:
    value: /datastorage/li/TCGA_GBMLGG
dataset:
    value: gbmlgg
epochs:
    value: 50
kfold:
    value: 5
lr:
    value: 2e-05
lr_policy:
    value: cosine
method:
    value: discrete
n_bins:
    value: 25
normalize:
    value: false
optimizer:
    value: Adam
patch_size:
    value: 16
pickle_path:
    value: ./datasets/TCGA_GBMLGG/tcga_gbmlgg.pkl
pretrained:
    value: WinKawaks/vit-tiny-patch16-224
results:
    value: ./results
seed:
    value: 42
stratify:
    value: true
verbose:
    value: true
visible_gpus:
    value: "1"
weight_decay:
    value: 0.01
workers:
    value: 0
