# environment
visible_gpus: '0'
seed: 42

# dataset
dataset: 'eyepacs'
task: 'classification'
data_root: '/datastorage/li/eyepacs/augmented_resized_V2'
checkpoints: './checkpoints'
results: './results'

kfold: 1 # disable kfold and use the official splits

# model
method: 'softmax' # 'softmax', 'ordcls'
backbone: 'resnet18'
pretrained: True
alpha: 0.5


# training
workers: 0
optimizer: 'Adam'
epochs: 50
batch_size: 256
lr: 2.0e-5
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
