# environment
visible_gpus: '1'
seed: 42

# dataset
dataset: 'gbmlgg'
task: 'survival'
data_root: "/datastorage/li/TCGA_GBMLGG"
pickle_path: "./datasets/TCGA_GBMLGG/tcga_gbmlgg.pkl"
checkpoints: './checkpoints'
results: './results'

kfold: 5
stratify: True
n_bins: 25

# model
method: 'deepsurv' # 'ordsurv', 'deephit', 'deepsurv', 'discrete', 'angularord', 'ordsoftmax'
backbone: 'resnet18'
patch_size: 16
pretrained: True
fold: 0

# ours
queue_size: 1024
lambda_rank: 0.1
ema_decay: 0.999
queue: True
virt_ratio: 0.
alpha: 0.4
aggregate: "max"

# training
workers: 0
optimizer: 'Adam'
epochs: 20
batch_size: 256
lr: 2.0e-4
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
