# environment
visible_gpus: '1'
seed: 42

# dataset
dataset: 'knee_osteoarthritis'
task: 'classification'
data_root: '/datastorage/li/knee-osteoarthritis'
checkpoints: './checkpoints'
results: './results'

kfold: 1 # disable kfold and use the official splits

# model
method: 'ordcls' # 'softmax', 'ordcls'
backbone: 'resnet18'
patch_size: 16
pretrained: True
alpha: 0.5


# training
workers: 0
optimizer: 'Adam'
epochs: 50
batch_size: 512
lr: 2.0e-4
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
