# environment
visible_gpus: '1'
seed: 42

# dataset
dataset: 'metabric'
feature_file: './datasets/METABRIC/cleaned_features_final.csv'
label_file: './datasets/METABRIC/label.csv'
checkpoints: './checkpoints'
results: './results'


# model
method: 'deepcdf'
backbone: 'MLP'
n_layers: 2
d_hid: 256
dropout: 0.2
activation: 'relu'


# training
workers: 0
optimizer: 'AdamW'
kfold: 5
epochs: 100
batch_size: 256
lr: 2.0e-5
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
