# environment
visible_gpus: '1'
seed: 42

# dataset
dataset: 'metabric_kfold'
task: 'survival'
feature_file: './datasets/METABRIC/cleaned_features_final.csv'
label_file: './datasets/METABRIC/label.csv'
checkpoints: './checkpoints'
results: './results'

kfold: 5
stratify: True
n_bins: 18

# model
method: 'deepcdf' # 'deepcdf', 'deephit', 'deepsurv', 'discrete', 'angularord', 'ordsoftmax', 'vmf'
backbone: 'MLP'
n_layers: 2
d_hid: 1024
dropout: 0.
activation: 'tanh'


# training
workers: 0
optimizer: 'Adam'
epochs: 100
batch_size: 256
lr: 2.0e-4
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
