# environment
visible_gpus: '0'
seed: 42

# dataset
dataset: 'metabric_deepsurv'
file_path: './datasets/deepsurv/metabric_IHC4_clinical_train_test.h5'
checkpoints: './checkpoints'
results: './results'

kfold: 1
stratify: True
n_bins: 4

# model
method: 'deepcdf' # 'deepcdf', 'deephit', 'deepsurv', 'discrete', 'angularord'
backbone: 'MLP'
n_layers: 2
d_hid: 1024
dropout: 0.
activation: 'tanh'


# training
workers: 0
optimizer: 'Adam'
epochs: 100
batch_size: 256
lr: 2.0e-5
lr_policy: 'cosine'
weight_decay: 0.
verbose: True
