# environment
visible_gpus: '0'
seed: 42

# dataset
dataset: 'support'
task: 'survival'
checkpoints: './checkpoints'
results: './results'

kfold: 5
stratify: True
n_bins: 25
normalize: False

# model
method: 'deepsurv' # 'ordsurv', 'deephit', 'deepsurv', 'discrete'
backbone: 'MLP'
n_layers: 2
d_hid: 1024
dropout: 0.
activation: 'tanh'

# ours
queue_size: 512
lambda_rank: 0.
ema_decay: 0.999
queue: False
virt_ratio: 1.0
alpha: 0.4

# training
workers: 0
optimizer: 'Adam'
epochs: 100
batch_size: 256
lr: 2.0e-4
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
