_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 80
            "3":
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
alpha:
    value: 0.4
backbone:
    value: vit
batch_size:
    value: 6
checkpoints:
    value: ./checkpoints
data_root:
    value: /datastorage/li/TCGA_GBMLGG
dataset:
    value: gbmlgg
ema_decay:
    value: 0.999
epochs:
    value: 20
fold:
    value: 0
kfold:
    value: 5
lambda_rank:
    value: 0.1
lr:
    value: 0.0002
lr_policy:
    value: cosine
method:
    value: deepsurv
n_bins:
    value: 25
optimizer:
    value: Adam
patch_size:
    value: 16
pickle_path:
    value: ./datasets/TCGA_GBMLGG/tcga_gbmlgg.pkl
pretrained:
    value: true
queue:
    value: true
queue_size:
    value: 128
results:
    value: ./results
seed:
    value: 42
stratify:
    value: true
task:
    value: survival
verbose:
    value: true
virt_ratio:
    value: 1
visible_gpus:
    value: "1"
weight_decay:
    value: 0.01
workers:
    value: 0
